services:
  localstack:
    image: localstack/localstack
    container_name: localstack_main
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/tmp/localstack"

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  localstack_data:
    driver: local
